"use client";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Home</title>
        {/* <link
			href="https://unpkg.com/aos@2.3.1/dist/aos.css"
			rel="stylesheet"
		/> */}
		{/* <link rel="stylesheet" type="text/css" href="css/custom.css" /> */}

        {/* <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script> */}
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        {/* <script src="../../public/js/jquery.slim.min.js"></script> */}
      </head>
      <body>{children}</body>
    </html>
  );
}
