"use client";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// import "./page.module.css"
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Home</title>
        {/* <link
			href="https://unpkg.com/aos@2.3.1/dist/aos.css"
			rel="stylesheet"
		/> */}
        {/* <link rel="stylesheet" type="text/css" href="css/custom.css" /> */}
        <script>AOS.init();</script>
        {/* <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script> */}
        <script
          src="https://code.jquery.com/jquery-3.7.1.min.js"
          async
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
