#local_backend: true
backend:
  name: git-gateway
  repo: anwaozo/LawyerSite
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "HomePage"
        file: "content/pages/home.md"
        fields:
          - name: "headerInfo"
            label: "Header Info"
            widget: "object"
            fields:
              - { label: "Logo", name: "logo", widget: "image" }
              - name: "menu"
                label: "Menu"
                widget: "list"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
          - name: "footerInfo"
            label: "Footer Info"
            widget: "object"
            fields:
              - { label: "Logo", name: "logo", widget: "image" }
              - name: "copyright"
                label: "Copyright"
                widget: "object"
                fields:
                  - {
                      label: "Copyright Text1",
                      name: "copyright1",
                      widget: "string",
                    }
                  - {
                      label: "Copyright Text2",
                      name: "copyright2",
                      widget: "string",
                    }
              - name: "quickMenu"
                label: "Quick Menu"
                widget: "list"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "socialMenu"
                label: "Social Menu"
                widget: "list"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
                  - { label: "Link Icon", name: "linkIcon", widget: "image" }

          - name: "metaTags"
            label: "Meta Tags"
            widget: "object"
            required: false
            fields:
              - { label: "Meta Title", name: "metatitle", widget: "string" }
              - {
                  label: "Meta Description",
                  name: "metaDescription",
                  widget: "string",
                }

          - name: "heroSection"
            label: "Hero Section"
            widget: "object"
            fields:
              - { label: "Hero Image", name: "heroImage", widget: "image" }
              - {
                  label: "Styled Heading",
                  name: "styledHeading",
                  widget: "string",
                }
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - name: "sectionLink"
                label: "Section Link"
                widget: "object"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "socialMediaIcons"
                label: "Social Media Icons"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Icon Path", name: "iconPath", widget: "string" }

          - name: "legalTeamSection"
            label: "Legal Team Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section SubTitle",
                  name: "subHeading",
                  widget: "text",
                }
              - name: "sectionLink"
                label: "Section Link"
                widget: "object"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "sectionInfo"
                label: "Section Info"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Displayed Number",
                      name: "displayedNumber",
                      widget: "string",
                    }

          - name: "legalPracticesSection"
            label: "Legal Practices Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                  required: false,
                }
              - {
                  label: "Section Image",
                  name: "sectionImage",
                  widget: "image",
                }
              - name: "sectionLink"
                label: "Section Link"
                widget: "object"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "sectionInfo"
                label: "Section Info"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Path", name: "path", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "image" }

          - name: "bussinessInformationSection"
            label: "Bussiness Information Section"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "string" }

          - name: "collegueSection"
            label: "Collegue Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                  required: false,
                }
              - name: "sectionLink"
                label: "Section Link"
                widget: "object"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "collegueInfo"
                label: "Collegue Info"
                widget: "list"
                fields:
                  - {
                      label: "Collegue Name",
                      name: "collegueName",
                      widget: "string",
                    }
                  - {
                      label: "Occupation",
                      name: "occupation",
                      widget: "string",
                    }
                  - { label: "Image", name: "image", widget: "image" }

          - name: "contactUsSection"
            label: "Contact Us Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                  required: false,
                }
              - name: "contactInfo"
                label: "Contact Info"
                widget: "object"
                fields:
                  - name: "phoneDetail"
                    label: "Phone Detail"
                    widget: "object"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - {
                          label: "Phone number",
                          name: "phoneNumber",
                          widget: "string",
                        }
                      - { label: "Icon", name: "icon", widget: "image" }
                  - name: "address"
                    label: "Address Detail"
                    widget: "object"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Address", name: "address", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "image" }
                  - name: "emailDetail"
                    label: "Email Detail"
                    widget: "object"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Email", name: "email", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "image" }
          - name: "ourPostsSection"
            label: "Our Posts Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                  required: false,
                }
              - name: "sectionLink"
                label: "Section Link"
                widget: "object"
                fields:
                  - { label: "Link Label", name: "linkLabel", widget: "string" }
                  - { label: "Link Path", name: "linkPath", widget: "string" }
              - name: "posts"
                label: "Posts Detail"
                widget: "list"
                fields:
                  - { label: "Post Type", name: "postType", widget: "string" }
                  - { label: "Post Title", name: "postTitle", widget: "string" }
                  - {
                      label: "Creation Date",
                      name: "creationDate",
                      widget: "datetime",
                    }
                  - { label: "Image", name: "image", widget: "image" }
          - name: "clientTestimonialSection"
            label: "Client Testimonial Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                  required: false,
                }
              - name: "clientTestimonial"
                label: "Client Testimonial"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - {
                      label: "Designation",
                      name: "designation",
                      widget: "string",
                    }
                  - {
                      label: "Testimonial",
                      name: "testimonial",
                      widget: "string",
                    }
                  - { label: "Image", name: "image", widget: "image" }
          - name: "evaluationSection"
            label: "Evaluation Section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section subTitle",
                  name: "subHeading",
                  widget: "text",
                }
              - name: "evaluationForm"
                label: "Evaluation Form"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - name: "fullName"
                    label: "Fullname field"
                    widget: "object"
                    fields:
                      - {
                          label: "Placeholder Text",
                          name: "placeholderText",
                          widget: "string",
                        }
                      - {
                          label: "fieldIcon",
                          name: "fieldIcon",
                          widget: "image",
                          required: false,
                        }
                  - name: "phone"
                    label: "Phone field"
                    widget: "object"
                    fields:
                      - {
                          label: "Placeholder Text",
                          name: "placeholderText",
                          widget: "string",
                        }
                      - {
                          label: "fieldIcon",
                          name: "fieldIcon",
                          widget: "image",
                          required: false,
                        }
                  - name: "email"
                    label: "Email field"
                    widget: "object"
                    fields:
                      - {
                          label: "Placeholder Text",
                          name: "placeholderText",
                          widget: "string",
                        }
                      - {
                          label: "fieldIcon",
                          name: "fieldIcon",
                          widget: "image",
                          required: false,
                        }
                  - name: "description"
                    label: "Description field"
                    widget: "object"
                    fields:
                      - {
                          label: "Placeholder Text",
                          name: "placeholderText",
                          widget: "string",
                        }
                      - {
                          label: "fieldIcon",
                          name: "fieldIcon",
                          widget: "image",
                          required: false,
                        }
                  - {
                      label: "Button Label",
                      name: "buttonText",
                      widget: "string",
                    }

      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - name: "MetaTags"
            label: "Meta Tags"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "metatitle", widget: "string" }
              - {
                  label: "Meta Description",
                  name: "metaDescription",
                  widget: "string",
                }
          - name: "WelcomeSection"
            label: "Welcome About Section"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Sub Heading", name: "subHeading", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

          - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    folder: "blog/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      # - {
      #     label: "Publish Date",
      #     name: "date",
      #     widget: "datetime",
      #     required: true,
      #   }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - label: "Properties"
    name: "properties"
    folder: "properties"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {
          label: "Property Name",
          name: "PropertyName",
          widget: "string",
          required: true,
        }
      - {
          label: "Amount of Property",
          name: "amount",
          widget: "string",
          required: true,
        }
      # - {
      #     label: "Publish Date",
      #     name: "date",
      #     widget: "datetime",
      #     required: true,
      #   }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: true,
        }
      - {
          label: "Number of Beds",
          name: "noofbeds",
          widget: "string",
          required: true,
        }
      - {
          label: "Number of Baths",
          name: "noofbaths",
          widget: "string",
          required: true,
        }
      - {
          label: "Number of Parking",
          name: "noofparking",
          widget: "string",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
